name: Hugo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: install pandoc
      run: |
           wget https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-1-amd64.deb
           sudo dpkg -i pandoc-2.10-1-amd64.deb
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true
          
    - name: Build
      run: |
       npm install -D --save autoprefixer
       npm install -D --save postcss-cli
       hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
