name: Production

# Trigger the workflow on pushes to the main branch, but only for changes in the .github/workflows and public directories
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'public/**'

  # Allow triggering the workflow manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # Uncomment the following line if using a Hugo theme as a Git submodule
          extended: true

      # Build the Hugo site
      - name: Build Hugo site
        run: hugo 
        
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Do not delete previews on each production deploy
          keep_files: true
          # Use the commit message as the deployment commit message
          commit_message: "deploy: ${{ github.event.head_commit.message }}"
