name: Production

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'public/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Install PostCSS dependencies
      - name: Install PostCSS
        run: |
          npm install -g postcss-cli autoprefixer

      # Build the Hugo site
      - name: Build Hugo site
        run: hugo
        
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          commit_message: "deploy: ${{ github.event.head_commit.message }}"
