name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-hugo-docsy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install PostCSS Plugins
        run: |
          npm install autoprefixer --save-dev

      - name: Configure PostCSS
        run: |
          echo 'module.exports = {
            plugins: [
              require("autoprefixer")
            ]
          }' > postcss.config.js

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
